FROM node:22-slim AS web-builder

COPY web/package.json /web/package.json
COPY web/package-lock.json /web/package-lock.json
COPY web/shared/ /web/shared/
COPY web/frps/ /web/frps/
WORKDIR /web
RUN npm config set registry https://registry.npmmirror.com
RUN npm install

WORKDIR /web/frps
RUN npm run build

FROM golang:1.26.1-alpine AS building

COPY . /building
COPY --from=web-builder /web/frps/dist /building/web/frps/dist
WORKDIR /building

ENV GOPROXY=https://mirrors.aliyun.com/goproxy/,direct
RUN env CGO_ENABLED=0 go build -trimpath -ldflags "-s -w" -tags frps -o bin/frps ./cmd/frps

FROM alpine:3

RUN apk add --no-cache tzdata

COPY --from=building /building/bin/frps /usr/bin/frps

ENTRYPOINT ["/usr/bin/frps"]
